# Generated by Django 3.0.5 on 2021-07-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_auto_20210706_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving_license_card',
            name='expires',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='expires',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
