# Generated by Django 3.0.5 on 2021-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_auto_20210719_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driving_license_card',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='driving_license_card',
            name='card_class',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driving_license_card',
            name='dob',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driving_license_card',
            name='driving_license_number',
            field=models.CharField(blank=True, default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driving_license_card',
            name='expires',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driving_license_card',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driving_license_card',
            name='nationality',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
